### ISSUE TITLE
Using HW SPI - compile fails

### ISSUE THREAD

**Issue by iliapenev** [schreinerman/AmbiqMicroApolloSDK#1]
Build fails when using real hardware SPI, not virtual IOM SPI.  Tested with e97cd412254079e8d47efaf08f62c5726334d0a7

IOMSTR_SWSPI is undefined and in following checks fails. 
https://github.com/schreinerman/AmbiqMicroApolloSDK/blob/master/apolloiom.c#L1911
https://github.com/schreinerman/AmbiqMicroApolloSDK/blob/master/apolloiom.c#L1940
https://github.com/schreinerman/AmbiqMicroApolloSDK/blob/master/apolloiom.c#L1958
https://github.com/schreinerman/AmbiqMicroApolloSDK/blob/master/apolloiom.c#L1982

Here is a simple patch.

```
diff --git a/apolloiom.h b/apolloiom.h
index 8ad002f..ddcbae2 100644
--- a/apolloiom.h
+++ b/apolloiom.h
@@ -352,6 +352,8 @@ extern "C"
 
 #if APOLLOSWSPI_ENABLED == 1 
 #define IOMSTR_SWSPI ((IOMSTR0_Type*)(IOMSTR0 + 4)) //create virtual SWSPI IOM interface
+#else
+#define IOMSTR_SWSPI 0xFFFFFFFF
 #endif
 
 #define IOM_PIN_NOTUSED  0xFF
```

**Comment by schreinerman** [comment]
Fixed but by checking if SWSPI is available
